#ifndef __STATUSES_H__
#define __STATUSES_H__

typedef enum {
	STATUS_OK = 0,
	STATUS_NOT_ZERO,
	STATUS_BUSY,
	STATUS_UNIMPLEMENTED,
	STATUS_WARNING_OUT_OF_SPEED,
	STATUS_ERROR_OUT_OF_TABLE,
	STATUS_SPINDLE_ON,
	STATUS_SPINDLE_OFF,
	STATUS_ERROR_ESTOP,
	STATUS_ERROR_INVALID_PARAMETER,
	STATUS_ERROR_OUT_OF_TEMPERATURERANGE,
	STATUS_ERROR_HEATER_NOT_TURNED_ON,
	STATUS_ERROR_HEATER_NOT_CONNECTED,
	STATUS_ERROR_EXTRUDER_NOT_HEATED,
	STATUS_ERROR_NOT_CALIBRATED,
	STATUS_ERROR_OUT_OF_POWER
} STATUSES;

char *statuses_getStatusText(STATUSES status);
int statuses_isErrorStatus(STATUSES status);

#endif //__STATUSES_H__
