#include "statuses.h"

char *statuses_getStatusText(STATUSES status) {
	switch(status) {
	case STATUS_OK:
		return "OK";
	case STATUS_NOT_ZERO:
		return "NOTZERO";
	case STATUS_BUSY:
		return "BUSY";
	case STATUS_UNIMPLEMENTED:
		return "UNIMPLEMENTED";
	case STATUS_WARNING_OUT_OF_SPEED:
		return "WARNING_OUT_OF_SPEED";
	case STATUS_ERROR_OUT_OF_TABLE:
		return "ERROR_OUT_OF_TABLE";
	case STATUS_SPINDLE_ON:
		return "SPINDLE_ON";
	case STATUS_SPINDLE_OFF:
		return "SPINDLE_OFF";
	case STATUS_ERROR_ESTOP:
		return "ERROR_ESTOP";
	case STATUS_ERROR_INVALID_PARAMETER:
		return "ERROR_INVALID_PARAMETER";
	case STATUS_ERROR_OUT_OF_TEMPERATURERANGE:
		return "ERROR_OUT_OF_TEMPERATURERANGE";
	case STATUS_ERROR_HEATER_NOT_TURNED_ON:
		return "ERROR_HEATER_NOT_TURNED_ON";
	case STATUS_ERROR_HEATER_NOT_CONNECTED:
		return "ERROR_HEATER_NOT_CONNECTED";
	case STATUS_ERROR_EXTRUDER_NOT_HEATED:
		return "ERROR_EXTRUDER_NOT_HEATED";
	case STATUS_ERROR_NOT_CALIBRATED:
		return "ERROR_NOT_CALIBRATED";
	case STATUS_ERROR_OUT_OF_POWER:
		return "ERROR_OUT_OF_POWER";
	}
	return "\0";
}

int statuses_isErrorStatus(STATUSES status) {
	switch(status) {
	case STATUS_ERROR_ESTOP:
	case STATUS_ERROR_INVALID_PARAMETER:
	case STATUS_ERROR_OUT_OF_TEMPERATURERANGE:
	case STATUS_ERROR_HEATER_NOT_TURNED_ON:
	case STATUS_ERROR_HEATER_NOT_CONNECTED:
	case STATUS_ERROR_EXTRUDER_NOT_HEATED:
	case STATUS_ERROR_NOT_CALIBRATED:
	case STATUS_ERROR_OUT_OF_POWER:
		return 1;

	case STATUS_OK:
	case STATUS_NOT_ZERO:
	case STATUS_BUSY:
	case STATUS_UNIMPLEMENTED:
	case STATUS_WARNING_OUT_OF_SPEED:
	case STATUS_ERROR_OUT_OF_TABLE:
	case STATUS_SPINDLE_ON:
	case STATUS_SPINDLE_OFF:
		return 0;

	}
	return 0;
}
