#ifndef _USB_HOST_PROTOCOL_H_
#define  _USB_HOST_PROTOCOL_H_

#define UHP_PATH ":<USB_MS_PATH>:"
#define UHP_KEYBOARD_CONNECTED ":<KEYBOARD_CONNECTED>:"
#define UHP_MOUSE_CONNECTED ":<MOUSE_CONNECTED>:"
#define UHP_KEYBOARD_REPORT ":<KEYBDHID>:"
#define UHP_MOUSE_REPORT ":<MOUSEHID>:"
#define UHP_ERROR ":<ERROR>:"
#define UHP_WAITFORDEVICE ":<WAIT_FOR_DEVICE>:"
#define UHP_FILEDONE ":<FILE_DONE>:"
#define UHP_FILEENTRY ":<FILE_ENTRY>:"
#define UHP_FILELINE ":<FILE_LINE>:"

#endif // _USB_HOST_PROTOCOL_H_